name: Build32

on:
  [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019
    
    # Run a job for each of the specified target architectures:
    strategy:
      matrix:
        arch:
          - win64
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Build
        continue-on-error: true
        run: |
          git submodule update --init --recursive --depth 1 --recommend-shallow
          bash patch-libpng.sh
          cd libpng/projects/vstudio
          msbuild.exe /property:Platform=Win32 /property:configuration="Release" vstudio.sln
      - name: moving
      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: releaselibpng-apng32
          path: libpng/projects/vstudio/Release
      # ...